# Assumes that the local repo is already fetched.

inputs:
  python_version:
    description: The Python version of the build toolchain to use.
    required: true
    default: 3.11

runs:
  using: composite
  steps:
    # Install deps
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip
        cache-dependency-path: '**/pyproject.toml'
    - shell: bash
      run: |
        pip install -e .[dev,mlflow] --config-settings editable_mode=strict
        pip freeze

